### ISSUE TITLE
Accidentally designed font too small

### ISSUE THREAD

**Issue by Davidemonaco** [mattlag/Glyphr-Studio-Help#11]
I accidentally designed my font three times smaller than it should be, so when i'm typing and switching between fonts in my documents, i also need to multiply the font size by three every time. Is there a way to do this directly with glyphr studio? As in, multiply font size by three for all glyphs, ligatures included?

I am aware there's the "Re-size all glyphs" function, but it asks for a Delta value, and i don't know how to use it.
Thanks in advance. :)

**Comment by mattlag** [comment]
Yes! Re-size all glyphs is the one you want.  The first step is understanding how big your font is currently, which you can find in Font Settings under Total Units per Em:
![image](https://user-images.githubusercontent.com/5897669/178326924-1bc3f50d-38c9-4a1b-8204-2d65f85f446a.png)

If you think you need to do something close to 3x, and you start at 1000, then you need to add 2000. I would use the Height field, plus the Maintain Aspect Ratio checkbox so that they scale by width as well:
![image](https://user-images.githubusercontent.com/5897669/178327990-aec265f8-c49c-4db7-9bd2-e87f20e7cf6e.png)

Finally you'll have to go back and update the Glyph Proportions > Key Metrics in Font Settings to match your new sizes.

This may take some trial and error, but luckily if you don't like the results you can just load your original project file in and try again :-)

I'm going to close this issue, but let me know if you have any other questions!
